In [1]:
import numpy as np

# why use numpy array
arr = np.array([1, 2, 3, 4, 5])
print(arr)


"""
NumPy (Numerical Python) is a library for fast numerical computing in Python.
Its main feature is the ndarray (N-dimensional array): a dense, typed, efficient array designed for math.

Much faster for math on large data (implemented in optimized C under the hood)
Powerful multi-dimensional arrays (1D, 2D, 3D…)
Vectorized operations (do math on whole arrays without Python loops)
Widely used in data science, ML, scientific computing
"""


[1 2 3 4 5]


'\nNumPy (Numerical Python) is a library for fast numerical computing in Python.\nIts main feature is the ndarray (N-dimensional array): a dense, typed, efficient array designed for math.\n\nMuch faster for math on large data (implemented in optimized C under the hood)\nPowerful multi-dimensional arrays (1D, 2D, 3D…)\nVectorized operations (do math on whole arrays without Python loops)\nWidely used in data science, ML, scientific computing\n'

In [ ]:
# list vs numpy (main differences)
# data types
# list can hold mixed datatypes


In [2]:
# THE QUESTION IS WHY NOT USE PYTHON ARRAY
# because numpy arr occupies less memory as compared to list

import sys

python_list = list(range(100))
print(python_list[:5])
print(sys.getsizeof(python_list))
sys.getsizeof(python_list[0]) * len(python_list)

[0, 1, 2, 3, 4]
856


2400

In [3]:
# list vs numpy
"""
Data types
list: can hold mixed types
numpy: usually holds one fixed dtype (e.g., all int32 or all float64)
"""

import numpy as np

print(np.array([1,2,3]).dtype)
print(np.array([1,2,3]).dtype)
print(np.array([2,3,4]).dtype)

int64
int64
int64


In [5]:
numpy_arr = np.arange(100)
print(numpy_arr[:5])
print(numpy_arr.nbytes)

"""
So it’s the same idea as Python’s range(100), but it returns a NumPy array.
numpy_arr = np.arrange(100)

This makes an array starting at 0 and going up to 99 (100 numbers total), step 1 by default:
start = 0 (default)
stop = 100 (not included)
step = 1 (default)

So it’s the same idea as Python’s range(100)

in numpy
.nbytes is “how many bytes of memory the array data uses”.
For np.arrange(100), NumPy usually uses int64 on 64-bit systems (8 bytes each):
100 elements × 8 bytes = 800 bytes

1 element (like 0) takes 8 bytes
100 elements take 100 × 8 = 800 bytes
"""



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
800


'\nSo it’s the same idea as Python’s range(100), but it returns a NumPy array.\nnumpy_arr = np.arrange(100)\n\nThis makes an array starting at 0 and going up to 99 (100 numbers total), step 1 by default:\nstart = 0 (default)\nstop = 100 (not included)\nstep = 1 (default\n\nSo it’s the same idea as Python’s range(100)\n\nin numpy\n.nbytes is “how many bytes of memory the array data uses”.\nFor np.arrange(100), NumPy usually uses int64 on 64-bit systems (8 bytes each):\n100 elements × 8 bytes = 800 bytes\n\n1 element (like 0) takes 8 bytes\n100 elements take 100 × 8 = 800 bytes\n'

In [ ]:
# why python occupies more memory ?
# python list array is heterogeneous. if you have python array one element can be string, another can be float and soon
# to support this it needs to store meta-data in the memory and the address are not contiguous, they might be scattered in the memory
# you can see the memory is fragmented so each of the byte store meta-data because of that total size occupied by python list is higher
# since memory is fragmented accessing element is also slower takes time while data is stored in contiguous memory location

In [11]:
# measuring performance in list

import time
size = 10
l1 = list(range(size))
l2 = list(range(size))
start = time.time()
l3 = [x+y for x, y in zip(l1, l2)]
print(l3)
end = time.time()

print("Python list took",end-start)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
Python list took 7.390975952148438e-05


In [ ]:
n1 = np.arange(size)
n2 = np.arange(size)

start = time.time()
n3 =  n1 + n2
end = time.time()

print("NumPy took",end-start)

# took less time because we do not need to do iteration (loops) instead we use Vectorized operations that is programming technique that performs a single operation on entire arrays (vectors/matrices) at once, rather than looping through each element,

In [ ]:
# benefit # convenient use of  inbuilt function
# less memory

In [16]:
# basic operations in numpy
# dimension in array

import numpy as np # Make sure to import numpy

# Pass a single list containing the rows
# revenue of quarter1
rev1 = np.array([[10, 12, 10], [11, 12, 13], [14, 15, 16]])

print(rev1)
print(rev1.shape) # 2 rows and 3 columns
print(rev1.ndim) # dimension
print(rev1[2,2]) #indexing

[[10 12 10]
 [11 12 13]
 [14 15 16]]
(3, 3)
2
16


In [19]:
rev1[1, 0] = 20
print(rev1) # numpy list is mutable, you can modify element at in place
print(rev1.tolist())
print(type(rev1.tolist()))

[[10 12 10]
 [20 12 13]
 [14 15 16]]
[[10, 12, 10], [20, 12, 13], [14, 15, 16]]
<class 'list'>


In [21]:
print(rev1.size)      # number of elements
print(rev1.itemsize) # size of each element in bytes - √=# for example, if dtype is int64 or float64


9
8


In [25]:
rev2 = np.array([[10, 12, 10], [11, 12, 13], [14, 15, 16]], dtype=np.int64)
print(rev2.itemsize) # 8 bytes per element

rev2 = np.array([[10, 12, 10], [11, 12, 13], [14, 15, 16]], dtype=np.int32)
print(rev2.itemsize) # 4 bytes per element

total_bytes = rev2.size * rev2.itemsize # Total memory used by the array # 9 elements * size
print(total_bytes)

8
4
36


In [28]:
# sorting use case in numpy
a = np.sort([3,2,1])
print(a)

b = np.sort([3,2,1])
print(b)

# sort 2D by rows
n =  np.array([[3,1,2],[9,7,8]])

"""
Think of it as 2 rows × 3 columns:
Row 0: [3, 1, 2]
Row 1: [9, 7, 8
"""


print(np.sort(n, axis=1))# sort each row
"""
axis=1 = sort each row
Row means “horizontal line”.
Row0 is: [3, 1, 2] → sorted → [1, 2, 3]
Row1 is: [9, 7, 8] → sorted → [7, 8, 9]
"""

"""
axis=0 = sort each column
Column means “vertical line”.
Column0 is: [3, 9] → sorted → [3, 9]
Column1 is: [1, 7] → sorted → [1, 7]
Column2 is: [2, 8] → sorted → [2, 8]

Why did axis=0 not change anything here?

Because in each column, the top number is already smaller than the bottom number:
3 < 9
1 < 7
2 < 8
So sorting columns doesn’t move anything.
"""


"""
For your array, axis=2 is not valid.

Why?

Your array:

m = np.array([[3, 1, 2],
              [9, 7, 8]])

has 2 dimensions:
m.ndim   # 2
m.shape  # (2, 3)


So the valid axes are:

axis = 0 → rows (vertical)
axis = 1 → columns (horizontal)
There is no axis 2.
AxisError: axis 2 is out of bounds for array of dimension 2
↓ axis=0 (down rows)

[ 3  1  2 ]  → axis=1 (across columns)
[ 9  7  8 ]

What each axis really means
🔹 axis = 0 → move down (vertical)

Operation happens column by column
Rows are compared within each column

🔹 axis = 1 → move across (horizontal)

Operation happens row by row
Columns are compared within each row
"""


[1 2 3]
[1 2 3]
[[1 2 3]
 [7 8 9]]


'\naxis=1 = sort each row\nRow means “horizontal line”.\nRow0 is: [3, 1, 2] → sorted → [1, 2, 3]\nRow1 is: [9, 7, 8] → sorted → [7, 8, 9]\n'

In [33]:
# In NumPy, “ones and zeros” usually means creating arrays filled with 1s or 0s.
a = np.zeros(5)        # [0. 0. 0. 0. 0.]
b = np.zeros((2, 3))
print(a)
print(b)

z = np.zeros((2, 3), dtype=np.int32)  # integer zeros
o = np.ones((2, 3), dtype=np.int64)   # integer ones
print(z)
print(o)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]


In [35]:
# √Like an existing array (same shape & dtype)
x = np.array([[5, 6], [7, 8]])

z = np.zeros_like(x)  # [[0 0]
                  #  [0 0]]
x1 = np.ones_like(x)   # [[1 1]
                  #  [1 1]]
print(x1, z)


[[1 1]
 [1 1]] [[0 0]
 [0 0]]


In [36]:
np.linspace(10, 20, 20)

array([10.        , 10.52631579, 11.05263158, 11.57894737, 12.10526316,
       12.63157895, 13.15789474, 13.68421053, 14.21052632, 14.73684211,
       15.26315789, 15.78947368, 16.31578947, 16.84210526, 17.36842105,
       17.89473684, 18.42105263, 18.94736842, 19.47368421, 20.        ])

In [49]:
flatten_list = x.flatten()
print(flatten_list)

import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)   # 2 rows, 3 columns
print(b)

# Flatten back to 1D
a.reshape(-1) # or a.ravel()

print(a.min())
print(a.max())
print(a.sum(axis=0))

[5 6 7 8]
[[1 2 3]
 [4 5 6]]
1
6
21


In [51]:
m = np.array([[3, 1, 2],
              [9, 7, 8]])
"""
axis=0 (sum down the rows = column-wise sum)

Add vertically in each column:
Col0: 3 + 9 = 12
Col1: 1 + 7 = 8
Col2: 2 + 8 = 10


axis=1 (sum across the columns = row-wise sum)
Add horizontally in each row:
Row0: 3 + 1 + 2 = 6
Row1: 9 + 7 + 8 = 24
"""

np.sum(m, axis=0)
np.sum(m, axis=1)
np.sum(m)
np.sqrt()


np.int64(30)