In [1]:
import numpy as np

In [2]:
# array operations - arithmetic operations on both matrics and vectors 
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a1

array([1, 2, 3, 4, 5])

In [3]:
a1 + a2 


array([ 7,  9, 11, 13, 15])

In [ ]:
# but operands could not be broadcast together with shapes (array size always be same for performing operations)

In [4]:
a1 - a2 

array([-5, -5, -5, -5, -5])

In [5]:
a2 - a1

array([5, 5, 5, 5, 5])

In [6]:
a2 * a2 

array([ 36,  49,  64,  81, 100])

In [9]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [10]:
a1 // a2 

array([0, 0, 0, 0, 0])

In [ ]:
# 7 / 2     # 3.5  (normal division — gives float)
# 7 // 2    # 3    (floor division — rounds down)

In [11]:
# broadcasting 

In [12]:
l = [10, 20, 30, 40]
arr = np.array(l)

In [13]:
for i in l:
    print(i + 10) # instead of applying loop we can apply arraus 

20
30
40
50


In [14]:
arr + 10

array([20, 30, 40, 50])

In [27]:
arr2 = np.arange(1, 26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [28]:
arr2 + 10


array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [31]:
arr2 =  arr2 + 10
arr2

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45]])

In [33]:
arr2 = arr2 * 10
arr2

array([[2100, 2200, 2300, 2400, 2500],
       [2600, 2700, 2800, 2900, 3000],
       [3100, 3200, 3300, 3400, 3500],
       [3600, 3700, 3800, 3900, 4000],
       [4100, 4200, 4300, 4400, 4500]])

In [34]:
# deep and shallow copy
a = np.arange(1, 21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [38]:
slice = a[:5]
slice = slice * 10
slice 

array([10, 20, 30, 40, 50])

In [56]:

# deep and shallow copy 
a = np.arange(1, 21)
a 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [57]:
slice = a[:5]
slice 

array([1, 2, 3, 4, 5])

In [58]:
# do broadcasting under slice 
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [59]:
a #

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [46]:
a[4:6] * 10

array([50, 60])

In [54]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [60]:
b = a 
b  = a.copy()

In [53]:
b[0] = 99 
b 

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [51]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [61]:
# shallow Copy vs Deep Copy in Arrays
# Shallow copy creates a new object but shares the same data. Deep copy creates a completely independent copy.

In [63]:
 # No Copy (Just a Reference)
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
b = arr            # no copy, just another name

b[0] = 99
print(arr)         # [99, 2, 3, 4, 5] ← original changed!
print(b is arr)    # True (same object)

[99  2  3  4  5]
True


In [64]:
 # Shallow Copy (View)
arr = np.array([1, 2, 3, 4, 5])
b = arr.view()     # shallow copy

b[0] = 99
print(arr)         # [99, 2, 3, 4, 5] ← original changed!
print(b is arr)    # False (different object, but shared data)

[99  2  3  4  5]
False


In [65]:
arr = np.array([1, 2, 3, 4, 5])
b = arr.copy()     # deep copy

b[0] = 99
print(arr)         # [1, 2, 3, 4, 5] ← original unchanged!
print(b is arr)    # False

[1 2 3 4 5]
False
