In [ ]:
# numpy is written in c which are compiled and super fast which is main reason numpy is 50x faster than python list 

In [1]:
# python list vs arrays

In [3]:
import numpy as np

In [5]:
# basic array creation using list
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [7]:
a = [1, 2, 3, "hello"]
a

[1, 2, 3, 'hello']

In [8]:
# NumPy arrays must have a single, consistent data type (dtype). When you give it mixed types like:
np.array(a) # NumPy doesn’t fail — instead it automatically upcasts everything to a type that can hold all elements and converts to string

array(['1', '2', '3', 'hello'], dtype='<U21')

In [9]:
# vector vs matrix (A vector is usually a 1D array vs A matrix is a 2D array.)

In [10]:
l = [[1,2, 3], [4,5,6], [7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
# array generation function 

In [13]:
np.arange(1, 10) # same as range function in list exclude last element

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr =  np.zeros(6) # vectors 
arr

array([0., 0., 0., 0., 0., 0.])

In [17]:
arr = np.zeros((4, 8)) # 4 rows and 8 columns
arr 

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [19]:
arr = np.linspace(1, 5, 2) # linspace =
#“I want exactly N numbers between two values” -> np.linspace(0, 10, 5) - “Give me 5 numbers from 0 to 10”
arr

array([1., 5.])

In [21]:
arr = np.linspace(0, 10, 5)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [22]:
arr = np.linspace(0, 1, 100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [27]:
# random number generation 
np.random.rand(10) # it is coming from 0 to 1 range (this is concept of normalization which will talk later) (0-1 normalization)

array([0.08177078, 0.14971583, 0.3652094 , 0.78158838, 0.68373722,
       0.48473338, 0.59411174, 0.05931961, 0.45032994, 0.29257297])

In [34]:
np.random.randn(10) # (-3 -> 3) # standarization 


array([ 7.53827199e-01, -1.51561205e+00, -2.08862183e-01,  9.72733468e-01,
        5.48264768e-04, -1.84838274e+00, -2.29632564e+00,  1.93729855e+00,
       -4.13672719e-01,  5.68893527e-01])

In [36]:

arr = np.array([[10, 2, 3], [4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
# Attributes = properties (data) of an object

# They store information
# You don’t call them (no ())

# Methods = functions that belong to an object

# They do something
# You must call them using ()
# a.reshape(3,2)

# ✔ reshape() is a method
# ✔ It changes how the array looks

In [41]:

arr.shape # 3 rows 3 columns 

(3, 3)

In [39]:
arr.size # 9 elements 

9

In [40]:
arr.dtype # data type

dtype('int64')

In [43]:
# array methods 
arr.min()
arr.max()

np.int64(9)

In [44]:
arr.sum()

np.int64(45)

In [47]:
# np.sum(a) → total sum
# axis=0 → column-wise
# axis=1 → row-wise

arr.sum(axis=0) 

array([12, 15, 18])

In [48]:
arr.sum(axis=1)

array([ 6, 15, 24])

In [49]:
arr.std()


np.float64(2.581988897471611)

In [52]:
arr.argmax() # max index

np.int64(8)

In [53]:
arr.argmin() # min index 

np.int64(0)

In [54]:

# reshaping and resizing a
arr = np.arange(1, 31)
arr 


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [58]:
# convert 1D (vector)to matrix 
# arr.reshape(5, 5) # 5 rows 5 columns # ValueError: cannot reshape array of size 30 into shape (5,5)a
# reshaping should be done based on total elements 
arr.reshape(5,6)
arr 


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
# array basic operations completed 

In [ ]:

# array indexing and slicing of vectors



In [59]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [60]:
# indexing 
arr[6]

np.int64(17)

In [61]:
arr[9]

np.int64(20)

In [63]:
# slicing # remove some portion # same a list slicing in python
arr[1:5]

array([12, 13, 14, 15])

In [64]:
arr[:5] # starting value will be default 0 

array([11, 12, 13, 14, 15])

In [65]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [66]:
# using steps 
arr[3::2]

array([14, 16, 18, 20])

In [ ]:
# array indexing and slicing of matix 
