In [2]:
import numpy as np

In [3]:
# Sales data for Quarter 1 (Matrix 1)
# Rows represent different products, columns represent different regions

q1 = np.array([
    [200, 220, 250],  # Product A
    [150, 180, 210],  # Product B
    [300, 330, 360]   # Product C
])

q2 = np.array([
    [209, 231, 259],  # Product A
    [155, 192, 222],  # Product B
    [310, 340, 375]   # Product C
])



[[409 451 509]
 [305 372 432]
 [610 670 735]]


#### Addition, Subtraction, Multiplication, Division

In [4]:
# combined sales of Q1 and Q2
q1 + q2 # no need to apply  loop here since this is vector operations

array([[409, 451, 509],
       [305, 372, 432],
       [610, 670, 735]])

In [5]:
# sales units growth in q2 compared to q1
# percent growth in quarter 2
q2 - q1

array([[ 9, 11,  9],
       [ 5, 12, 12],
       [10, 10, 15]])

In [6]:
# % sales units growth in q2 compared to q1
# % Growth = (New − Old) / Old × 100
(q2 - q1) / q1 * 100


array([[4.5       , 5.        , 3.6       ],
       [3.33333333, 6.66666667, 5.71428571],
       [3.33333333, 3.03030303, 4.16666667]])

In [41]:
# ROWS IS PRODUCTS AND COLUMN IS REGION, USA, CANADA, CHINA
"""
Units sold = 100
Price per unit = 100
Revenue = 100 × 100 = 10,000

Revenue (also called Gross Revenue)

What it is:
The total money earned from sales before anything is deducted.

Includes:
Sales value
Before discounts
Before returns
Before taxes, fees, commissions
"""
prices = np.array([
    [10, 12, 11],  # Prices for Product A in different regions
    [8,  9,  10],  # Prices for Product B
    [15, 16, 17]   # Prices for Product C
])

# prices of each product - for revenue (q1 unit of sales * prices)
q1_revenue = q1 * prices
q1_revenue

array([[2000, 2640, 2750],
       [1200, 1620, 2100],
       [4500, 5280, 6120]])

In [42]:
# flat discount given 20 %
# Multiplying by a percentage means “take that fraction”, not “increase”
"""
Multiplying by a number less than 1 → value decreases
Multiplying by a number greater than 1 → value increases
10,000 × 2   = 20,000  (increase)
10,000 × 1  = 10,000  (same)
10,000 × 0.5 = 5,000  (decrease)
10,000 × 0.02 = 200   (big decrease)

"""

q1_discounts = q1_revenue*0.02
q1_discounts

array([[ 40. ,  52.8,  55. ],
       [ 24. ,  32.4,  42. ],
       [ 90. , 105.6, 122.4]])

In [43]:
 # Revenue and Net Revenue are related but not the same.
"""
Net Revenue
What it is:
The money the company actually keeps from sales after deductions.
Revenue minus:
Discounts
Returns / refunds
Allowances
Sales commissions
(sometimes) indirect taxes

 """
net_revenue = q1_revenue - q1_discounts
net_revenue

array([[1960. , 2587.2, 2695. ],
       [1176. , 1587.6, 2058. ],
       [4410. , 5174.4, 5997.6]])

In [36]:
np.sum(q1_discounts)

564.2

#### Dot, Cross Product

In [9]:
# first column is square footage, second is bedrooms

features = np.array([
    [2000, 3], # house 1
    [1800, 2]  # house 2
])

weights = np.array([150, 50000])

price = np.dot(features, weights)
price

array([450000, 370000])

In [10]:
""""
what is a vector?
A vector is just an arrow with:
a direction
a length
→
↑

DOT PRODUCT (·) — “How much together?” - “Are these two arrows pointing in the same direction?
example1 - →   → (same direction) => Dot product = big positive number


Example 2: 90° (perpendicular)
→
↑
Dot product = 0

Example 3: Opposite direction
→   ←

Dot product = negative

A = (1, 0)
B = (1, 0)

A · B = 1*1 + 0*0 = 1   (same direction)


A = (1, 0)
B = (0, 1)

A · B = 1*0 + 0*1 = 0   (perpendicular)


CROSS PRODUCT (×) — “Which way is perpendicular?”
“If I stand on A and turn toward B, which way is ‘out’?”
→   then ↑

A = (1, 0, 0)
B = (0, 1, 0)

A × B = (0, 0, 1)

"""



SyntaxError: invalid syntax (2349965623.py, line 2)

In [51]:
c = np.array([1,2,3])
d = np.array([4,5,6])
np.cross(c,d)

array([-3,  6, -3])